#!/bin/bash

echo ""
echo "Example of valid command input: bash main.sh EXAMPLE"
echo ""
echo "Test №1"
echo "Input parameter:  Hello"
echo "Output result:    $(bash main.sh Hello)"
echo ""
echo "Test №2"  
echo "Input parameter: 123"
echo "Output result:   $(bash main.sh 123)"
echo ""
echo "Test №3"  
echo "Input parameter: 123 123"
echo "Output result:   $(bash main.sh 123 123)"
echo ""
echo "Test №4"  
echo "Input parameter: abc 123"
echo "Output result:   $(bash main.sh abc 123)"
echo ""
echo "Test №5"  
echo "Input parameter: Hello, world!"
echo "Output result:   $(bash main.sh Hello, world!)"
echo ""
